import { ApiDocumentation, ApiEndpoint, ApiParameter, ApiResponse, ApiRequestHeader, ApiRequestBody } from '../types';

// Re-export main types for convenience
export type { ApiDocumentation, ApiEndpoint, ApiParameter, ApiResponse, ApiRequestHeader, ApiRequestBody };

export interface ApiDocumentationProps {
  /** API documentation data generated by the scanner */
  data: ApiDocumentation;
  /** Custom CSS classes for the container */
  className?: string;
  /** Whether to show search functionality */
  searchable?: boolean;
  /** Whether to show statistics cards */
  showStats?: boolean;
  /** Default expanded state for categories */
  defaultExpanded?: boolean;
  /** Custom theme configuration */
  theme?: 'light' | 'dark' | 'system';
  /** Callback when an endpoint is selected */
  onEndpointSelect?: (endpoint: ApiEndpoint) => void;
}

export interface EndpointCardProps {
  endpoint: ApiEndpoint;
  index: number;
  onSelect?: (endpoint: ApiEndpoint) => void;
}

export interface TableOfContentsProps {
  endpoints: ApiEndpoint[];
  onEndpointSelect: (endpoint: ApiEndpoint, index: number) => void;
  searchQuery?: string;
  defaultExpanded?: boolean;
}

export interface SearchInputProps {
  onSearch: (query: string) => void;
  placeholder?: string;
  className?: string;
}

export interface StatsCardsProps {
  totalEndpoints: number;
  totalCategories: number;
  version?: string;
  generatedAt?: string;
}
